gruut/signer-android

- .travis.yml
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/signup/SignUpViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/KeystoreUtil.java
- script/deploy.sh
- 함수명 정리
- 주석 추가
- deploy채널 변경...
> KeystoreUtil refactoring

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/proto/GruutNetwork.proto
> EDIT Proto method name rename

- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/MessageHeader.java
* Main version 1로 셋팅
* 헤더 출력시 맨 앞 두 바이트는 [ 0x47, 0x10 ] 으로 출력 됨
> EDIT - Main version setting

- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgJoin.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgResponse1.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgSignature.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgSuccess.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgAccept.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgChallenge.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgRequestSignature.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgResponse2.java
- app/src/test/java/com/gruutnetworks/gruutsigner/model/MsgPackerTest.java
- app/src/test/java/com/gruutnetworks/gruutsigner/model/PackMsgResponse1Test.java
* Gson이 친절하게 super class까지 serialize해서 메세지 포맷이 깨지는 버그 수정
> BUGFIX - serialize/deserialize with gson

- app/build.gradle
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/PreferenceUtil.java
- app/src/main/res/layout/dashboard_fragment.xml
- app/src/main/res/layout/setting_fragment.xml
- app/src/main/res/values/strings.xml
- Setting버튼을 눌러 통신 할 Merger의 주소를 설정할 수 있음
- 이전에 테스트했던 주소는 Preference에 저장되어 자동으로 세팅 됨
- 잘못된 IP 주소를 방지하기 위한 필터가 적용되어있음
> Merger address를 UI에서 설정할 수 있도록 함

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* ByteBuffer 대신 ByteArrayOutputStream을 사용
> BUGFIX - signing할 때 buffer 에러 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgSignature.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/test/java/com/gruutnetworks/gruutsigner/model/MsgPackerTest.java
- app/src/test/java/com/gruutnetworks/gruutsigner/model/PackMsgSignatureTest.java
- app/src/test/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModelTest.java
*  동일한 timestamp를 사용하지 않는 부분 수정
*  byte 처리 에러 수정
*  MSG_SSIG packing시 hmac을 붙이도록 세팅
> BUGFIX - 서명 과정에서 발생한 버그 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/KeystoreUtil.java
- app/src/test/java/com/gruutnetworks/gruutsigner/util/KeystoreUtilTest.java
* sha256으로 변환한 key를 hex로 인코딩하여 preference에 저장해 뒀는데, 이 key를 hex 디코딩하지 않고 사용해서 생긴 버그
> EDIT - hmac 생성 시 버그 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/ErrorMsgException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/MsgUnpacker.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- MSG_ACCEPT, MSG_REQ_SSIG를 전송받았을 경우에는 HMAC 검증이 필요함
- HMAC을 검증하여 invalid할 경우, 에러메세지를 출력한다.
> ADD - 전송 받은 데이터의 hmac을 검증하는 부분 추가

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/ErrorMsgException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgChallenge.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/AuthGeneralUtil.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/SecurityConstants.java
*  MSG_CHALLENGE에서 포함되어 오는 timestamp 값을 가지고 유효한 메세지인지 판단한다.
*  현재 시간이 전송 받은 timestamp와 100ms 이상 차이가 나면 invalid한 메세지라고 판단하여 에러를 띄운다.
> ADD - 메세지 유효기간 체크

- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/GruutConfigs.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/MsgHeader.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/MsgUnpacker.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
:warning: #37 을 merge한 후, base branch를 check-expiration에서 develop으로 변경 후 merge해주세요 :warning:
* 체인과 관련된 정보, 설정과 관련된 값을 Config파일로 분리하였습니다.
* Local chain id, 버전 정보, grpc timeout 값 등
* 이외에 private으로 변경 가능한 변수와 메소드를 정리하였습니다.
> EDIT - Config 파일 분리

- app/src/main/java/com/gruutnetworks/gruutsigner/util/AuthGeneralUtil.java
Reverts gruut/signer-android#44
> Revert "GEN-158: JIRA 연동 테스트"

- app/build.gradle
- app/src/main/java/com/gruutnetworks/gruutsigner/model/SignedBlock.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/SignedBlockDao.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/AppDatabase.java
- app/src/test/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModelTest.java
* SQLite 기반의 Room을 내부 DB로 사용함
* column은 chain_id, block_hgt이며, primary key는 이 두개의 column을 combine하여 사용함
* 지지 서명 생성 직전, 해당 chain id와  block height를 DB에 insert함.
* duplicate key로 fail이 된다면 exception 처리.
> GEN-49: #ADD - 서명한 블록의 chian id와 block height를 저장

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/AuthGeneralUtil.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/SecurityConstants.java
* Merger가 보낸 MSG_SSIG_REQ의 time 값이 10분을 벗어난다면 서명하지 않고 버림
> GEN-48: Merger가 보낸 블록의 시간 유효성을 검사한다

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/PreferenceUtil.java
- app/src/main/res/layout/dashboard_fragment.xml
* Merger 2의 로그 창, 세팅 창 등 UI 컴포넌트들을 추가함
* 세팅의 경우 merger1인지 merger2인지에 따라 따로 관리(enum으로)
> GEN-168: 2개의 Merger를 관리할 수 있도록 UI 변경

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingFragment.java
* setting에서 입력한 ip/port를 가져오는 순서가 잘못되어 있던 버그 수정
> # EDIT - 사소한 UI 버그 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
> GEN-170: # EDIT - channel 따로 관리하도록 수정 #time 30m #finish

- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgJoin.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgResponse1.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/PackMsgSuccess.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgAccept.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgChallenge.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgResponse2.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* 메세지 타입에서 `sender`는 모호하기 때문에 플레이어 타입이 명확할 땐 `mID` 또는 `sID`를 명확하게 쓰기로 함
* Pack 해야 하는 메세지는 sID, Unpack 해야 하는 메세지는 mID로 수정
*  Merger 측이 수정되었을 때 테스트 해봐야 함
* ⚠️ 테스트 후에 merger 측과 같은 때에 머지 해야 함
> GEN-178: # EDIT - 메세지 모델링 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/ErrorMsgException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/MsgUnpacker.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgAccept.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgChallenge.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgRequestSignature.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgResponse2.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* 전송 받은 메세지의 헤더에 있는 Sender 값과, 메세지 바디의 json 안에 있는 mID 값과 일치하는지 확인한다.
* 일치하지 않는다면 에러메세지와 함께 세션 종료.
#52 머지 후 base를 develop으로 변경하여 머지 요망
> GEN-181: # ADD - 받은 메세지의 헤더와 내용을 비교하여 검증한다 #time 15m #finish

- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/GruutConfigs.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/SettingFragment.java
* 사소한 UI 버그 수정 - 해당하는 머저만 refresh되도록 수정
* Auto Refresh - 커넥션이 끊기면 5초 이후 자동으로 붙도록 수정
> GEN-191: # EDIT -테스트 위한 수정

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/signup/SignUpViewModel.java
- app/src/main/res/values/strings.xml
* GA에서 제공되는 에러코드와 메세지별로 에러 처리
* NPE에 대한 exception 처리 코드 추가
> GEN-199: # ADD - GA Error handling #finish

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/ErrorMsgException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/TypeError.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/UnpackMsgError.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/test/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModelTest.java
* MSG_TYPE이 0xFF로 올 때에 대한 exception 처리 추가
* 상세 에러메세지를 보여줌
> GEN-198: # ADD - Error message handling #finish

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/AuthUtilException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/GruutConfigs.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/res/layout/dashboard_fragment.xml
- app/src/main/res/values/strings.xml
1.  Signer Nonce 관련
* signer nonce를 머저별로 관리하고 있지 않아 실패할 확률이 있었음. merger nonce와 마찬가지로 map으로 관리하여 필요한 값을 꺼내오도록 수정
2. ECDH Key 생성 관련
* 동시에 2개의 Merger에 join을 시작할때 각각 KeyPair를 생성하기 시작함
* 먼저 만들어진 key는 쓸 수 없게 됨
* 화면 진입과 동시에 ECDH 키를 생성하도록 수정
3. UI 관련
* ip/port 설정 후 refresh 버튼이 뜨는 버그 수정
* Refresh 버튼에 TextView 추가
* Auto Refresh timeout 10초로 변경
> GEN-203: 두 개의 Merger와 통신이 불안정한 버그 수정

- .travis.yml
- README.md
- app/build.gradle
- script/deploy.sh
루이지 테스트를 수행중입니다. 버그 리포팅이 포함됩니다.
> WIP: Release/luigi  테스트

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* MSG_SSIG_REQ 메세지 안에 있는 Timestamp를 이용하여 지지서명을 하도록 변경
* 기타 사소한 Lint 에러 수정
* privte/pacakge-private으로 변경 가능한 부분 수정
* 무의미한 null init 삭제
* 무의미한 catch 문 삭제
* 기타 수정
> GEN-205: # BUGFIX - 지지서명의 timestamp 변경

- script/deploy.sh
> # EDIT - deploy message

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* 실행시킨 Thread가 적절히 종료되지 않아 Memory leak이 발생할 우려가 있음
* 기존의 AsyncTask를 처리하는 방법은 Memory Leak을 유발할 수 있어 Weak Reference로 처리하도록 함
* join 하는 thread도 static inner class로 생성하여 Weak Reference로 관리
> GEN-207: # BUGFIX - thread bug

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
* 지지서명을 생성하는 중에 실패하더라도 채널을 끊지는 않도록 수정
> GEN-214: # BUGFIX - 지지서명 생성에 실패하더라도 채널 유지

- app/src/main/java/com/gruutnetworks/gruutsigner/exceptions/ErrorMsgException.java
- app/src/main/java/com/gruutnetworks/gruutsigner/model/MsgUnpacker.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/proto/GruutNetwork.proto
* 더 간편하게 proto를 변경하고 통신 방식을 수정함
* 처음부터 grpc streaming channel을 연 채로 통신 수행
* 로그 정리
* 아래 Merger의 PR과 같이 업데이트 되어야 함.
https://github.com/gruut/enterprise-merger/pull/216
* AsyncTask 수행 중, 화면을 끄거나 하여 channel이 ShutDown되면 AsyncTask의 결과 값을 보낼 곳이 없어 앱이 죽는다.
* 해당 부분에 try catch문을 추가하여 처리함
> GEN-233: # REFAC - Grpc 변경 #finish

- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/Merger.java
- app/src/main/java/com/gruutnetworks/gruutsigner/gruut/MergerList.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresetListAdapter.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresetSelectedListener.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresetSelectedListner.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresettingFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresettingViewModel.java
- app/src/main/res/drawable/item_selector.xml
- app/src/main/res/layout/dashboard_fragment.xml
- app/src/main/res/layout/preset_item.xml
- app/src/main/res/layout/presetting_fragment.xml
- app/src/main/res/values/colors.xml
1. 랜덤한 Merger 선택
* gruut/MergerList.java 에 Merger의 이름과 IP, Port를 기입한다.
* 최초 실행 시, MergerList에서 랜덤하게 하나의 Merger를 선택하여 세팅한다.
* 재 실행 시에는 최초 실행 때 설정 된 Merger에 붙는다.
2. Merger 세팅
* Setting 버튼을 누르면 MergerList에 저장되어 있는 Merger의 목록이 나타난다.
* 원하는 Merger를 선택하고 확인 버튼을 누르면 해당 Merger에 붙는다.
* 재 실행 시에는 이 때 설정해 둔 Merger에 붙는다.
> GEN-230: # ADD - merger 프리셋 설정

- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/DashboardViewModel.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/dashboard/PresettingFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/ui/signup/SignUpFragment.java
- app/src/main/java/com/gruutnetworks/gruutsigner/util/PreferenceUtil.java
- app/src/main/res/layout/sign_up_fragment.xml
- app/src/main/res/values/strings.xml
base branch 변경 후 머지해야 함!
* Merger Setting -> Select a merger to connect
* 랜덤하게 선택 될 때 중복되지 않도록
* Dashboard 진입 전 안내메세지(최초 실행 시에만)
> GEN-244: # EDIT - 친절한 Signer가 되어보자!

- app/src/main/java/com/gruutnetworks/gruutsigner/model/SignUpResponse.java
* GA에서 전송하는 포맷에 맞춰 변경(pem -> certPem)
> # EDIT - ga response json 형식 변경
